.travis.yml, CHANGELOG.md, example/lib/main.dart, example/test_driver/main_test.dart, lib/capture_screen.dart, lib/config.dart, lib/fastlane.dart, lib/image_magick.dart, lib/process_images.dart, lib/resources.dart, lib/screens.dart, lib/screenshots.dart, pubspec.yaml, test/screenshots_test.dart
Also prep for removal of timeouts in integration test of example
=> Released v0.1.5

lib/screenshots.dart, lib/utils.dart, test/screenshots_test.dart
instead of first available device
Note: merging to dev from gh-pages (branch created in error)
=> Fix for #25 to get available device for highest iOS version

lib/resources/script/android-wait-for-emulator, lib/screenshots.dart, lib/utils.dart, test/screenshots_test.dart
Addresses #25 
@yvanvds let me know if this works
=> Get available device for highest iOS version instead of first available device

CHANGELOG.md, lib/config.dart, lib/resources/script/android-wait-for-emulator, pubspec.yaml
Improved handling of iOS simulator info provided by Apple
=> Released v0.1.6

.travis.yml, lib/config.dart, lib/utils.dart, test/regression_test.dart
Fixes part two of  #25 
Also did some refactoring and added regression test for part two of #25 
Also fixes needing extra job for deploying artifacts (does it in one job now)
=>  Removed iOS version names that do not have available devices

.travis.yml, bin/main.dart, lib/config.dart, lib/screenshots.dart, lib/utils.dart, test/regression/issue_29.dart
=> Added feature to find the latest emulator for an android device in config file

lib/utils.dart
Pull output simultaneously from both `stdout` and `stderr` so that in the event there is `stderr` output interspersed among `stdout`, no blocking on `stdout` occurs.
Fixes #40.
=> fix: read stdout and stderr concurrently to avoid blocking on stdout

lib/screenshots.dart
=> Await locale change

README.md
Readme for version 1.0.1 uses outdated config object.
=> Change readme to use configInfo object

.travis.yml, example/screenshots_CI.yaml
Created separate screenshots.yaml for CI (skip android for faster builds for now)
=> Created separate screenshots.yaml for CI

CHANGELOG.md, pubspec.yaml
Added record/compare feature #65
=> Released v1.1.0 

README.md, bin/main.dart, example/screenshots.yaml, example/screenshots_CI.yaml, example/test_driver/main.dart, example/test_driver/main_test.dart, lib/src/config.dart, lib/src/run.dart, lib/src/utils.dart, test/screenshots_test.dart
Modified test to get localized text for current locale and use when finding FAB button
Also:
- Handled locale change when running on real devices
- Fixed waiting for locale change to complete
- Removed warning about running in multiple locales
- Updated README
Fixes #19 
Fixes #20
=> Resolved localization issue

CHANGELOG.md, pubspec.yaml
=> Released v1.1.1

bin/main.dart, test/common.dart, test/screenshots_test.dart
=> Improved check for adb path

CHANGELOG.md, pubspec.yaml
- Added archive feature to collect screenshots of all runs for reporting, etc... #77 #81
- Improved detection of adb path #79
=> Released v1.2.0

CHANGELOG.md, pubspec.yaml
=> Published v1.3.0

lib/src/config.dart
=> Removed dependency on processing objects from Yaml package

bin/main.dart, example/test_driver/main_test.dart, lib/screenshots.dart, lib/src/capture_screen.dart, lib/src/config.dart, lib/src/fastlane.dart, lib/src/image_processor.dart, lib/src/run.dart, lib/src/utils.dart, lib/src/validate.dart, test/all_tests.dart, test/config_test.dart, test/daemon_test.dart, test/env_test.dart, test/fastlane_test.dart, test/frame_test.dart, test/process_images_test.dart, test/screenshots_test.dart, test/screenshots_yaml_test.dart, test/src/config_test.dart
Added getters and methods for all access to config.
Created a ConfigDevice to access device settings.
Removed access to raw map.
Integrated with code base.
=> Refactored Config

lib/src/daemon_client.dart, lib/src/run.dart, lib/src/utils.dart, lib/src/validate.dart, test/daemon_client_test.dart, test/daemon_test.dart, test/regression/issue_29.dart, test/run_test.dart, test/screenshots_test.dart
Added a device and emulator object that is returned from the daemon client in place of a Map.
Integrated into code base and tested
=> Refactored daemon client

.travis.yml, appveyor.yml, bin/main.dart, lib/src/base/process.dart, lib/src/daemon_client.dart, lib/src/fastlane.dart, lib/src/image_processor.dart, lib/src/orientation.dart, lib/src/run.dart, lib/src/utils.dart, lib/src/validate.dart, test/daemon_client_test.dart, test/daemon_test.dart, test/fastlane_test.dart, test/screenshots_test.dart, test/screenshots_yaml_test.dart
=> Added verbose mode

pubspec.yaml
Should resolve analysis issue on https://pub.dev/packages/screenshots
(useful for older installs, flutter/flutter#39932 updated to 0.16.0)
fixes #124
=> Relaxed intl package versioning #124

CHANGELOG.md, README.md, pubspec.yaml
Relaxed intl package versioning #124
=> Released v2.0.2+1

.codecov.yml, bin/main.dart, lib/screenshots.dart, lib/src/base/process_common.dart, test/all_tests.dart, test/base/all_tests.dart, test/base/process_common_test.dart, test/config_test.dart
=> Added check of flutter path

CHANGELOG.md, lib/src/base/process_common.dart, lib/src/utils.dart, pubspec.yaml, test/utils_test.dart
Fixed test of CI env var when no CI env var defined 
Closes #146
=> CI env bug

lib/src/run.dart, test/run_test.dart
=> Fix for #152

CHANGELOG.md, pubspec.yaml
- fixes bug with running multiple tests #152
=> Released v2.1.1

.cirrus.yml, .travis.yml, example/screenshots_ios.yaml, lib/src/run.dart, lib/src/utils.dart, pubspec.yaml, test/run_test.dart, test/utils_test.dart
=> Fix for missing .GlobalProperties on iOS 13 simulator

example/screenshots.yaml, lib/src/config.dart, test/config_test.dart
=> Restored check for disabling framing on landscape

.cirrus.yml, .travis.yml, example/screenshots_ios.yaml, lib/src/fastlane.dart, lib/src/image_processor.dart, lib/src/run.dart, lib/src/utils.dart, test/fastlane_test.dart, test/image_processor_test.dart, test/screenshots_test.dart
- Fixed messaging when using default fastlane directories
- Included error messaging on command error
=> Fixed fastlane messaging and error handling

lib/resources/screens.yaml
Temporary solution until the actual frame images are added.
Take it or leave it :)
=> Add iPhone 11 Pro Max to screens.yaml
